# Generated by Django 3.1.2 on 2020-10-24 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('fromDate', models.CharField(max_length=10)),
                ('toDate', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('technology', models.TextField()),
                ('image', models.FilePathField(path='/img')),
            ],
        ),
    ]
